apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: gcr.io/kubernetes-hello-world-1385/app:0001
        imagePullPolicy: IfNotPresent
        name: app
